CREATE TABLE IF NOT EXISTS tags(
lastCrawlTimeUTC DOUBLE NOT NULL,
count DOUBLE NOT NULL,
score VARCHAR(50) NOT NULL,
uri VARCHAR(50) NOT NULL,
label VARCHAR(50) NOT NULL,
PRIMARY KEY (count),
FOREIGN KEY (lastCrawlTimeUTC) REFERENCES mainTableName(lastCrawlTimeUTC)
);

CREATE TABLE IF NOT EXISTS pages(
lastCrawlTimeUTC DOUBLE NOT NULL,
docId VARCHAR(50) NOT NULL,
title VARCHAR(100) NOT NULL,
diffbotUri VARCHAR(50) NOT NULL,
text VARCHAR(6700) NOT NULL,
humanLanguage VARCHAR(50) NOT NULL,
html VARCHAR(8900) NOT NULL,
siteName VARCHAR(50) NOT NULL,
gburl VARCHAR(200) NOT NULL,
pageUrl VARCHAR(150) NOT NULL,
timestamp VARCHAR(50) NOT NULL,
date VARCHAR(50) NOT NULL,
estimatedDate VARCHAR(50) NOT NULL,
type VARCHAR(50) NOT NULL,
parentUrlDocId VARCHAR(50) NOT NULL,
icon VARCHAR(100) NOT NULL,
PRIMARY KEY (lastCrawlTimeUTC)
);

CREATE TABLE IF NOT EXISTS videos(
lastCrawlTimeUTC DOUBLE NOT NULL,
diffbotUri CHAR(50) NOT NULL,
url CHAR(600) NOT NULL,
primary VARCHAR(50) NOT NULL,
PRIMARY KEY (diffbotUri),
FOREIGN KEY (lastCrawlTimeUTC) REFERENCES mainTableName(lastCrawlTimeUTC)
);

CREATE TABLE IF NOT EXISTS images(
lastCrawlTimeUTC DOUBLE NOT NULL,
naturalHeight DOUBLE NOT NULL,
diffbotUri VARCHAR(50) NOT NULL,
naturalWidth DOUBLE NOT NULL,
primary VARCHAR(50) NOT NULL,
width DOUBLE NOT NULL,
url VARCHAR(100) NOT NULL,
height DOUBLE NOT NULL,
PRIMARY KEY (naturalHeight),
FOREIGN KEY (lastCrawlTimeUTC) REFERENCES mainTableName(lastCrawlTimeUTC)
);